### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by SForney54** [JemRF/rf_tools#1]
Downloaded directly from here and configured with my Raspberry Pi 3 B+. Ran the test with the RF_Config.py and received error message:

python rf_config.py 01 HELLO
SENT     : 01HELLO
An exception of type IOError occurred. Arguments:
(25, 'Inappropriate ioctl for device')
[Errno 25] Inappropriate ioctl for device
NO REPLY

Assumed something has to do with the switching device that isn't responding? I've looked up for any known error message in documentation but no luck. 

Thanks,

**Comment by davemacrae** [comment]
Exactly the same thing happened to me today when trying to test the IOT Gateway on a PI Zero.

**Comment by JemRF** [comment]
Its caused by a misconfigured serial port. See here for details on how to solve.

https://jemrf.github.io/RF-Documentation/faq.html
